### ISSUE TITLE
Does this plugin work on Windows devices?

### ISSUE THREAD

**Issue by jiankai82** [AlexanderZaytsev/react-native-i18n#58]
Does this plugin work on Windows devices?  I see there is a windows folder with source code in it.  I installed this plugin and tried to use it on my Windows desktop.  I manually linked this plugin to my project.  However, my project does not even build after the plugin is added.  This is the build error:

cannot convert from 'ReactNative.Modules.RNI18n.ReactNativeI18n' to 'ReactNative.Modules.Core.IReactPackage'.

Looks like ReactNativeI18n does not implement the IReactPackage interface.

Any help is appreciated.

**Comment by zoontek** [comment]
@jiankai82 I tried to make it work on 2.0.0 (see https://github.com/AlexanderZaytsev/react-native-i18n/commits/2.0.0 ) but it's hard work for so little usage.
You will can use the my C# to implement a native module if you want.
